POST http://localhost:1234/user/signup HTTP/1.1
content-type: application/json

{
    "email":"rishu@gmail.com",
    "password":"12@343"
}

###

POST http://localhost:1234/user/signin HTTP/1.1
content-type: application/json

{
    "email":"rishu@gmail.com",
    "password":"12@343"
}

###

POST http://localhost:1234/topic/add HTTP/1.1
content-type: application/json

{
    "topic_name":"Trie",
    "difficulty":"hard",
    "time_taken":"5"
}

###

GET http://localhost:1234/topic/show HTTP/1.1
content-type: application/json

###

POST http://localhost:7777/companies/patch HTTP/1.1
content-type: application/json

{
    "id":"13",
    "name":"Hero",
    "email":"hero@gmail.com"
}

###

GET http://localhost:7777/invoices/get HTTP/1.1
content-type: application/json

###

POST http://localhost:7777/invoices/post HTTP/1.1
content-type: application/json

{
    "user_id":"119",
    "from_id":"13",
    "to_id":"4",
    "amount":"500"
}

###

POST http://localhost:7777/invoices/patch HTTP/1.1
content-type: application/json

{
    "user_id":"119",
    "from_id":"13",
    "to_id":"4",
    "amount":"1000"
}

